### PR TITLE
Dynamic pages

### PR DESCRIPTION
**Pull request by johanjanssens**
Note: This PR required joomlatools/joomlatools-framework#151 for testing

Dynamic pages allow you to render data that comes from different sources. The default type of collection is a list of pages. 

## Definition

A collection is defined in the frontmatter of the page

```yaml
collection: 
   state:
        limit: int 
        offset: int
        order: desc/descending/asc/ascending/shuffle
        sort: string
        category: string
        sitemap: bool
        path: url
        recurse: bool
        level: int
    layout: string
```
### Layout 

The layout allows you to specific the specific layout that should be used for each of the pages returned. The layout is only used of the page doesn't have it's own layout defined. 

### State

- **limit:** the pagination limit
- **offset**: the pagination offset
- **order**: the pages ordering
- **sort**: the sorting of the pages, receives a data column name, to sort by date use 'date'
- **category**: return pages from a specific category only, by default the category is the name of the folder the pages are nested in.
- **sitemap**: if true will return only those pages who have sitemap set to 'true'. Used to create a sitemap
- **path**:  The base path to use for the collection, default is the path where the collection is defined in
- **recurse**: Recurse child folders, default 0
- **level**: Maximum level to recurse, default 

## Methods

This PR adds two new methods.

1. The `pages($path, $state)` method can be used to access the collection and will return an iterator or an iterable object.

The `$state` method parameters can be a php array, or a use a shorthand syntax of 'option:value, option:value'. Example: `pages('blog', 'limit:3, order:shuffle'); `

Note: it's possible to only retrieve the folders and not the pages by calling getFolders() on the returned entity. Example: `pages('blog', 'recurse: true')->getFolders()`

2. The `page($path)` method can be used to access a specific page and will return the page object.

## Templates

This PR adds two core templates

- com:pages.pages.newsfeed.rss to render newsfeeds
- com:pages.pages.sitemap.xml to render a sitemap

Support has also been added for different page formats, to define a template for a specific format just add it to the page. Example: `/blog/index.rss.php` for a page that returns rss, call it in the url as http://mysite.com/blog.rss

## Example

Following example will render a list of the titles of the different post. The files are fetched from the same folder as the page.

```
<ul>
<? foreach(pages() as $page): ?>
    <li><?= $page->title ?></li>
<?endforeach?>
</ul>
```

## Notes

- This PR also adds a `date()` template function to make it easier to format a date. Example: `date($page->date, 'format')`. The format parameter is optional if no format is defined the date will rendered using the Joomla default date format.

### CODE REVIEW

**Comment by raeldc** [comment]
@johanjanssens,

This works. But I have a question. 

Example, I want a page that displays posts inside the `/blog` folder in a list. Naturally it will contain an `index.html.php` file which will be the index file that will generate the list of blog posts. But since the collection fetches all the files within the same folder, the collection also includes the index file(itself). So knowing that, if I want to avoid the index file when generating the list of posts, I would have to use a conditional statement. Is this how it's meant to work?

**Comment by johanjanssens** [comment]
The 'index' file is considered a special file and not included in the listing. See: https://github.com/joomlatools/joomlatools-pages/pull/14/commits/e67fade15c8f33227d074b5ebcb1da88ebb46a3b#diff-a2269cbff63cb47994023df2d6c26ec9R58

**Comment by johanjanssens** [comment]
@raeldc That is strange because it's working fine here. Can you test again? What is your setup?

**Comment by raeldc** [comment]
@johanjanssens,

Was there something you haven't pushed into the Framework? I can't it to work.

**Comment by johanjanssens** [comment]
@raeldc Everything has been pushed and is working on my end for this branch. Contact me on chat to explain your setup and what you are trying to do.

**Comment by raeldc** [comment]
@johanjanssens,

When my index file is named `index.php`, the collection ignores it. But when the index file is named `index.html.php`, it is included in the collection. 

Otherwise, everything works as expected.

**Comment by johanjanssens** [comment]
Should use index.php from now on, that way I don't need to code against both file formats.

**Pull request merged**
